# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=750, verbose_name='内容'),
        ),
    ]
