# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-21 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='%Y%m/product', verbose_name='主要图片'),
        ),
    ]
