# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-21 19:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20190721_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classify',
            options={'ordering': ['-reorder'], 'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-reorder'], 'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-reorder'], 'verbose_name': '商品标签', 'verbose_name_plural': '商品标签'},
        ),
        migrations.AlterField(
            model_name='product',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes', to='mall.Classify', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='mall.Tag', verbose_name='标签'),
        ),
    ]
