# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='地址是否有效'),
        ),
    ]
