# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-21 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190720_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatar', verbose_name='用户头像'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(default=0, verbose_name='用户级别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='地址是否有效'),
        ),
    ]
