# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-21 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190721_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户基础信息', 'verbose_name_plural': '用户基础信息'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['is_default', '-updated_at'], 'verbose_name': '用户地址信息', 'verbose_name_plural': '用户地址信息'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户详细信息', 'verbose_name_plural': '用户详细信息'},
        ),
    ]
