# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-21 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190721_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginrecord',
            options={'verbose_name': '用户登陆信息', 'verbose_name_plural': '用户登陆信息'},
        ),
    ]
